Universe	= vanilla
Executable 	= JetVal_Script.sh
notification 	= Never
Output  	= /sphenix/user/verkest/analysis/JS-Jet/JetValidation/macro/logs/condor$(process).out
Error           = /sphenix/user/verkest/analysis/JS-Jet/JetValidation/macro/logs/condor$(process).err
Log  		= /tmp/condor_verkest_$(process).log
Arguments 	= "$(Process)"	
Initialdir  	= /sphenix/user/verkest/analysis/JS-Jet/JetValidation/macro/
request_memory = 4096MB
concurrency_limits=CONCURRENCY_LIMIT_DEFAULT:1000
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue 286 
